# Generated by Django 5.0.7 on 2024-07-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='behavior_data',
        ),
        migrations.AddField(
            model_name='child',
            name='data_file',
            field=models.FileField(null=True, upload_to='child_data/'),
        ),
    ]
