# Generated by Django 5.0.7 on 2024-07-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0002_remove_child_behavior_data_child_data_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='data_file',
        ),
    ]
