# Generated by Django 5.0.7 on 2024-07-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0003_remove_child_data_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(null=True, upload_to='child_data/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChildCSVData', to='guard.child')),
            ],
        ),
    ]
