# Generated by Django 5.0.7 on 2024-07-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0004_csv_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_data',
            name='file_type',
            field=models.CharField(choices=[('oximeter values graph', 'Oximeter Values Graph'), ('ppG sensor graph', 'PPG Sensor Graph'), ('perspiration sensor', 'Perspiration Sensor')], max_length=1000, null=True),
        ),
    ]
