# Generated by Django 5.0.7 on 2024-07-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0006_csv_data_is_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='name',
        ),
        migrations.AddField(
            model_name='child',
            name='dateofbirth',
            field=models.DateTimeField(null=True),
        ),
    ]
